import requests

ZOOM_BEARER_TOKEN = "eyJzdiI6IjAwMDAwMiIsImFsZyI6IkhTNTEyIiwidiI6IjIuMCIsImtpZCI6IjIwOWE4MjY5LTA2MzktNDhmOC1iNTcwLThkNjk2MDU3NTc5ZCJ9.eyJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiJadlYtQXB1elN6R2t4c2EtYVNzV0dRIiwidmVyIjoxMCwiYXVpZCI6IjQ4NTI2N2U2Njk0YTkyNTMyYzgxYmQ5N2FkNDAyNzZkZjg5ZjNhYWI1ZmZhNGJlZWQ2OTM0MjhmMmVjMTZjMzIiLCJuYmYiOjE3NTg4MDYzNzYsImNvZGUiOiJYZXBrbUVEYlJjaS14UEdodERRUkxRUGk1RTRwaG1IU3YiLCJpc3MiOiJ6bTpjaWQ6RlNKZlNvV2tSQUNHMUE5aGN4Z0ptZyIsImdubyI6MCwiZXhwIjoxNzU4ODA5OTc2LCJ0eXBlIjozLCJpYXQiOjE3NTg4MDYzNzYsImFpZCI6IlJVc04yTDNhUzA2aS1YZnVxVUdCVWcifQ.dvPbzjBY5c_DtcY44tV-RgMpP8k_ofCHsCzvl7KoXRpbTTjuvOB38io2-nbEk_rerlhf_RStWcyZd3STeSi2dA"
meeting_id = "82079002963"   # Use meeting ID, no spaces

url = f"https://api.zoom.us/v2/past_meetings/{meeting_id}/polls"

headers = {"Authorization": f"Bearer {ZOOM_BEARER_TOKEN}"}

resp = requests.get(url, headers=headers)
print("Status:", resp.status_code)
print("Response:", resp.json())
